### PR TITLE
31533 - add Disclosures to CS

### PR DESCRIPTION
**Pull request by zachary-horvath**

### CODE REVIEW

**Comment by mhak** [comment]
The disclosure should be its own content type which can be referenced by both insights and investment pages. Please see acceptance criteria

**Comment by zachary-horvath** [comment]
"/" has an error due to RecentArticles revisions. Will work with newest changes from that PR. Other routes work => ex. https://finserv-contentstack-git-feature-431533-disclosures-xc-entium.vercel.app/insights/the-feeling-ismutual.

**Comment by mhak** [comment]
please add disclosure to investment pages as well

**Comment by zachary-horvath** [comment]
> please add disclosure to investment pages as well

To the landing page or [slug] route? It's on the [slug] route for both insights and investments.

**Comment by mhak** [comment]
for the slug route. I'm not seeing any disclosures besides the one you linked. Can we set a few defaults to all?

**Comment by zachary-horvath** [comment]
> for the slug route. I'm not seeing any disclosures besides the one you linked. Can we set a few defaults to all?

I'm unable to set defaults for reference fields in CS. I added the disclosures to the rest of the investment pages.

**Pull request merged**
