### PR TITLE
31226 - add PageAnchorBanner to CS

### PR DESCRIPTION
**Pull request by zachary-horvath**

### CODE REVIEW

**Comment by mhak** [comment]
i'm getting a server error:
https://finserv-contentstack-git-feature-331226-page-a-12c2af-xc-entium.vercel.app/investments/broad-u-s-tips-index-exchange-traded-fund
image

**Comment by zachary-horvath** [comment]
> i'm getting a server error: https://finserv-contentstack-git-feature-331226-page-a-12c2af-xc-entium.vercel.app/investments/broad-u-s-tips-index-exchange-traded-fund image

Missing .env variable or an issue with the xcore api being updated possibly? My most recent PR (which builds on this) appears to be working. **https://github.com/XCentium/xcore.accelerator/pull/117**

**Comment by mhak** [comment]
i tried updating vercel with NEXT_PUBLIC_XCORE_MOCK_API_URL and redeploying. Still error:

https://finserv-contentstack-git-feature-331226-page-a-12c2af-xc-entium.vercel.app/investments/broad-u-s-tips-index-exchange-traded-fund

**Comment by zachary-horvath** [comment]
> i tried updating vercel with NEXT_PUBLIC_XCORE_MOCK_API_URL and redeploying. Still error:
> 
> https://finserv-contentstack-git-feature-331226-page-a-12c2af-xc-entium.vercel.app/investments/broad-u-s-tips-index-exchange-traded-fund

Is it worth going back to this branch when we have a working PR built on top of this? **https://github.com/XCentium/xcore.accelerator/pull/117**

**Comment by mhak** [comment]
no lets close all the ones before. we'll take #117

**Pull request closed without merging**
